### ISSUE TITLE
Area Map Default Zoom Lock

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-applicantmaps#30]

**Comment by chriswhong** [comment]
Default view for Area Maps should be a set buffer of screen space around the 600ft project buffer.  

Scrolling and Zooming should be disabled, but the user should be able to unlock the zoom and scroll to make changes to the map.

**Comment by trbmcginnis** [comment]
I started this in a branch called disable-zoom. Right now I only have a 'checkbox' working for whether a property is true/false but the map is not responding. I was trying to use map.scrollZoom.disable() from mapbox.

**Comment by andycochran** [comment]
I've pushed some changes to the `disable-zoom` branch. Also realized it's not just zoom but all interaction we want to disable/enable. Otherwise, you can still pan, double click to zoom, pinch zoom, rotate, etc. 

It might be possible to refactor this. @chriswhong, could you review it? Seems redundant to do this in multiple places:  
```
    // disable interactions
    map.scrollZoom.disable();
    map.boxZoom.disable();
    map.dragRotate.disable();
    map.dragPan.disable();
    map.keyboard.disable();
    map.doubleClickZoom.disable();
    map.touchZoomRotate.disable();
```

I tried doing the `disable()`/`enable()` in a computed property, but the app barfed.

**Comment by andycochran** [comment]
I also wasn't sure the best way to go about resetting the defaults. I've added a button to the UI. But we're already messing with bounds in so many places. 🤷‍♂️
