### ISSUE TITLE
Users can't create a new zoning district inside of a larger one

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#393]
Users will frequently want to draw a new zoning district inside of a larger one that will surround it on all sides. Essential they want to carve a donut hole inside an larger district, and create a new district in the hole. Currently, this is not possible.

Options to resolve this:
- ~Automatically cut out and delete the overlap somehow~
- **Allow users to have overlapping layers but have them add free form labels for the exterior district so it can be discerned from the inside one.**

**Comment by hannahkates** [comment]
After discussing with TRD, we agreed on option 2. We will allow users to draw overlapping polygons, but we will provide a specially styled point text label (that matches the zoning district labels) to resolve any labeling issues as needed.

Our next step is now to build that zoning district label annotation tool, allowing the user to choose what style of text they want.

**Comment by andycochran** [comment]
I think this isn't a new annotation tool, but changes to the existing text tool to allow for size and style options (in the same popup when you enter the text).

**Comment by allthesignals** [comment]
![image](https://user-images.githubusercontent.com/5004319/53348329-d80fe800-38e8-11e9-8091-2c9b9f8dc2f4.png)

My understanding of this issue is that the user will simply draw a new polygon, overlapping an existing polygon, with a new or configurable option on the text annotation tool. 

Only downstream issues I can think of is in the rezoning calculation - rezoning calculation may not like to see overlapping polygons, or it may not detect the change. Or it may work just fine.
