### ISSUE TITLE
Users can't create a new district type

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#411]
New districts do get created sometimes, and the app doesn't currently allow the user to input a new zoning district label

**Comment by hannahkates** [comment]
This is connected to #393. We will allow users to place text labels to create a new label in these scenarios. However, they still need to be able to select something in the drop down menu to complete their polygon. We should add a "new, non-existent zoning district" option in the drop down menu for them to select.

**Comment by allthesignals** [comment]
~Hmmm I'm not totally clear on what the issue is... it sounds like _sometimes_ when we create a district in any of the zoning types, it doesn't allow the ability to change the zoning district? ~

~This isn't what I'm seeing....~

Alright, I think I get it. How about having an "----OR----" with a text field underneath?

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/5004319/53348978-1c4fb800-38ea-11e9-8bf5-db800b0b867f.png">

**Comment by hannahkates** [comment]
We want a text input box immediate below drop down menu that shows up conditionally if user selects "need to propose new district"

**Comment by trbmcginnis** [comment]
ember-power-select has this addon --> [ember-power-select-with-create](https://github.com/cibernox/ember-power-select-with-create)
