### ISSUE TITLE
[Draw] Deleting a polygon vertex when there are only 3 causes error, breaks app

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#423]
To replicate: 
- Draw a square with 4 points 
- Delete one of the points to make a triangle (delete works fine)
- Delete another of the points 
- The app goes into an unusable state with error:  `Uncaught Error: coordinates must only contain numbers`

**Comment by allthesignals** [comment]
Yeah, this is probably because we're manually triggering deletions on vertices. When you delete 2 of 4 vertices, it's not a valid geometry object, so we need some handling or preferably we need to get mapbox-gl-draw to handle this internally somehow. Manually triggering certain behaviors probably skips whatever validation catches mbgl draw has set up.
